using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace DiscGolf.Models
{
    public class Course
    {
        public int CourseID { get; set; } //Autogenerated by EF

        [Required(ErrorMessage = "Please enter the course name.")]
        public string CourseName { get; set; }

        public ICollection<Hole> Holes { get; set; } //Navigation Property
        public ICollection<GamePlayed> GamesPlayed { get; set; } //Navigation Property

        public string Slug =>
            CourseName?.Replace(' ', '-').ToLower();
    }
}