using System;
using System.ComponentModel.DataAnnotations;

namespace DiscGolf.Models
{
    public class Hole
    {
        public int HoleID { get; set; } //auto-generated by EF

        public int CourseID { get; set; } //Foreign Key
        public Course Course { get; set; } //Navigation property
        
        [Required(ErrorMessage = "Please enter par for the hole: ")]
        [Range(1, 15, ErrorMessage = "Par must be between 1 and 15")]
        public int? Par { get; set; }

        [Required(ErrorMessage = "Please enter distance for the hole in feet: ")]
        public double? Distance{ get; set; } //in feet

        [Required(ErrorMessage = "Please enter the sequence number: ")]
        public int? SequenceNumber { get; set; }
    }
}
