using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DiscGolf.Models
{
    public class Player
    {
        public int PlayerID { get; set; }//auto-generated by EF

        [StringLength(25, ErrorMessage = "Name must be less than 25 characters")]
        public string Name { get; set; }
        
        [Required(ErrorMessage = "Please enter your username.")]
        [StringLength(25, ErrorMessage = "Username must be less than 25 characters")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Please enter your password.")]
        [StringLength(50, ErrorMessage = "Password must be less than 50 characters")]
        public string Password { get; set; }

        public ICollection<GamePlayed> GamesPlayed { get; set; }

        public string Slug =>
            Name?.Replace(' ', '-').ToLower();
    }
}
