using System.ComponentModel.DataAnnotations;

namespace DiscGolf.Models
{
    public class Course
    {
        public int CourseID { get; set; } //Autogenerated by EF

        [Required(ErrorMessage = "Please enter the course name.")]
        public string CourseName { get; set; }

        [Required(ErrorMessage = "Please enter the number of holes.")]
        [Range(1, 20, ErrorMessage = "Number of holes must be between 1 and 20")]
        public int? NumberOfHoles { get; set; }

        [Required(ErrorMessage = "Please enter the par for the course.")]
        [Range(1, 100, ErrorMessage = "Par for the course must be positive and less than 100")]
        public int? CoursePar { get; set; }

        [Required(ErrorMessage = "Please enter par for each hole.")]
        public string HolePar { get; set; }

        public string Slug =>
            CourseName?.Replace(' ', '-').ToLower();
    }
}


/*
 * Can't store a list as a list of ints to the databse table
 * I can store primitive data types
 * Need a list to hold the par for each holea
 * Can create a string that holds par for each hole
 *      and save that string to the databse
 * Will just need to split the string up when
 *      working with the course
 * 3-3-3-3-2-4-3-4-3
 */